# Download base image ubuntu 18.04
FROM ubuntu:bionic

# LABEL about the custom image
LABEL maintainer="salvadorhm@gmail.com"
LABEL version="0.1"
LABEL description="This is a ubuntu:18.04 image with PHP7 and SQLite3"

ENV DEBIAN_FRONTEND=noninteractive


# Install packages

RUN apt-get update
RUN apt-get install -y git
RUN apt-get install -y ne
RUN apt-get install -y sqlite3
RUN apt-get install -y php
RUN apt-get install -y mc
RUN apt-get install -y php-sqlite3
RUN apt-get clean
